---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice-{{ .Values.EnvironmentID }}
spec:
  selector:
    matchLabels:
      app: adservice-{{ .Values.EnvironmentID }}
  template:
    metadata:
      labels:
        app: adservice-{{ .Values.EnvironmentID }}
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: gcr.io/google-samples/microservices-demo/adservice:v0.8.0
        ports:
        - containerPort: 9555
        env:
        - name: PORT
          value: "9555"
        resources:
          requests:
            cpu: 200m
            memory: 180Mi
          limits:
            cpu: 300m
            memory: 300Mi
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          grpc:
            port: 9555
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          grpc:
            port: 9555
---
apiVersion: v1
kind: Service
metadata:
  name: adservice-{{ .Values.EnvironmentID }}
spec:
  type: ClusterIP
  selector:
    app: adservice-{{ .Values.EnvironmentID }}
  ports:
  - name: grpc
    port: 9555
    targetPort: 9555