---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-{{ .Values.EnvironmentID }}
spec:
  selector:
    matchLabels:
      app: frontend-{{ .Values.EnvironmentID }}
  template:
    metadata:
      labels:
        app: frontend-{{ .Values.EnvironmentID }}
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: default
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          image: gcr.io/google-samples/microservices-demo/frontend:v0.8.0
          ports:
          - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
              httpHeaders:
              - name: "Cookie"
                value: "shop_session-id=x-readiness-probe"
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
              httpHeaders:
              - name: "Cookie"
                value: "shop_session-id=x-liveness-probe"
          env:
          - name: PORT
            value: "8080"
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "productcatalogservice-{{ .Values.EnvironmentID }}:3550"
          - name: CURRENCY_SERVICE_ADDR
            value: "currencyservice-{{ .Values.EnvironmentID }}:7000"
          - name: CART_SERVICE_ADDR
            value: "cartservice-{{ .Values.EnvironmentID }}:7070"
          - name: RECOMMENDATION_SERVICE_ADDR
            value: "recommendationservice-{{ .Values.EnvironmentID }}:8080"
          - name: SHIPPING_SERVICE_ADDR
            value: "shippingservice-{{ .Values.EnvironmentID }}:50051"
          - name: CHECKOUT_SERVICE_ADDR
            value: "checkoutservice-{{ .Values.EnvironmentID }}:5050"
          - name: AD_SERVICE_ADDR
            value: "adservice-{{ .Values.EnvironmentID }}:9555"
          # # ENV_PLATFORM: One of: local, gcp, aws, azure, onprem, alibaba
          # # When not set, defaults to "local" unless running in GKE, otherwies auto-sets to gcp
          # - name: ENV_PLATFORM
          #   value: "aws"
          - name: ENABLE_PROFILER
            value: "0"
          # - name: CYMBAL_BRANDING
          #   value: "true"
          # - name: FRONTEND_MESSAGE
          #   value: "Replace this with a message you want to display on all pages."
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-{{ .Values.EnvironmentID }}
spec:
  type: ClusterIP
  selector:
    app: frontend-{{ .Values.EnvironmentID }}
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-external-{{ .Values.EnvironmentID }}
spec:
  type: LoadBalancer
  selector:
    app: frontend-{{ .Values.EnvironmentID }}
  ports:
  - name: http
    port: 80
    targetPort: 8080
