apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatch-{{ .Values.EnvironmentID }}
  labels:
    service: dispatch-{{ .Values.EnvironmentID }}
spec:
  replicas: 1
  selector:
    matchLabels:
      service: dispatch-{{ .Values.EnvironmentID }}
  template:
    metadata:
      labels:
        service: dispatch-{{ .Values.EnvironmentID }}
    spec:
      {{ if .Values.psp.enabled }}
      serviceAccountName: robot-shop-{{ .Values.EnvironmentID }}
      {{ end }}
      containers:
      - name: dispatch-{{ .Values.EnvironmentID }}
        image: {{ .Values.image.repo }}/rs-dispatch:{{ .Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          # agent networking access
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      restartPolicy: Always
