apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-{{ .Values.EnvironmentID }}
  labels:
    service: mongodb-{{ .Values.EnvironmentID }}
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mongodb-{{ .Values.EnvironmentID }}
  template:
    metadata:
      labels:
        service: mongodb-{{ .Values.EnvironmentID }}
    spec:
      {{ if .Values.psp.enabled }}
      serviceAccountName: robot-shop-{{ .Values.EnvironmentID }}
      {{ end }}
      containers:
      - name: mongodb-{{ .Values.EnvironmentID }}
        image: {{ .Values.image.repo }}/rs-mongodb:{{ .Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 27017
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
      restartPolicy: Always
