apiVersion: v1
kind: Service
metadata:
  labels:
    service: mongodb-{{ .Values.EnvironmentID }}
  name: mongodb-{{ .Values.EnvironmentID }}
spec:
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
  selector:
    service: mongodb-{{ .Values.EnvironmentID }}
