apiVersion: v1
kind: Service
metadata:
  labels:
    service: mysql-{{ .Values.EnvironmentID }}
  name: mysql-{{ .Values.EnvironmentID }}
spec:
  ports:
  - name: mysql-{{ .Values.EnvironmentID }}
    port: 3306
    targetPort: 3306
  selector:
    service: mysql-{{ .Values.EnvironmentID }}
