apiVersion: v1
kind: Service
metadata:
  name: payment-{{ .Values.EnvironmentID }}
  labels:
    service: payment-{{ .Values.EnvironmentID }}
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: payment-{{ .Values.EnvironmentID }}
