apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-{{ .Values.EnvironmentID }}
  labels:
    service: rabbitmq-{{ .Values.EnvironmentID }}
spec:
  replicas: 1
  selector:
    matchLabels:
      service: rabbitmq-{{ .Values.EnvironmentID }}
  template:
    metadata:
      labels:
        service: rabbitmq-{{ .Values.EnvironmentID }}
    spec:
      {{ if .Values.psp.enabled }}
      serviceAccountName: robot-shop-{{ .Values.EnvironmentID }}
      {{ end }}
      containers:
      - name: rabbitmq-{{ .Values.EnvironmentID }}
        image: rabbitmq:3.7-management-alpine
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 5672
        - containerPort: 15672
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
      restartPolicy: Always
