apiVersion: v1
kind: Service
metadata:
  labels:
    service: redis-{{ .Values.EnvironmentID }}
  name: redis-{{ .Values.EnvironmentID }}
spec:
  ports:
  - name: redis-{{ .Values.EnvironmentID }}
    port: 6379
    targetPort: 6379
  selector:
    service: redis-{{ .Values.EnvironmentID }}
