apiVersion: v1
kind: Service
metadata:
  name: web-{{ .Values.EnvironmentID }}
  labels:
    service: web-{{ .Values.EnvironmentID }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{.Values.hostname}}.{{.Values.domain}}
    external-dns.alpha.kubernetes.io/ttl: "60"
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: web-{{ .Values.EnvironmentID }}
  {{ if .Values.nodeport }}
  type: NodePort
  {{ else }}
  type: LoadBalancer
  {{ end }}
---
{{if .Values.ocCreateRoute}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: web-{{ .Values.EnvironmentID }}
spec:
  to:
    kind: Service
    name: web-{{ .Values.EnvironmentID }}
{{end}}
